### PR TITLE
Slice renderer window: Display data value and measure distances.

### LINKED ISSUE #145: Display values and distances in slice rendering window
Relevant scripts: `SliceRenderingEditorWindow.cs`

**TODO:**
- Make slice rendering window look nicer
- Show data value on mouse click
- Allow measuring distances (see [RadiAnt DICOM Viewer](https://www.radiantviewer.com/) for reference ). Also see [this](https://github.com/mlavik1/UnityVolumeRendering/issues/140#issuecomment-1354192942) request.

### PR DESCRIPTION
**Pull request by mlavik1**
**Changes to slice renderer window:**
- Added 3 input modes: 
  - Move: Move the plane:
  - Inspect: Select a position by clicking, and display data value.
  - Measure: Click and drag to measure distance between two points.

https://user-images.githubusercontent.com/6906872/208314302-96f699a4-bfe5-445f-8cfc-46f28578c07d.mp4

This should resolve #145 

**TODO:**
- Fixed slice view size? (just clamp it instead).
- Clean up the buttons / UX for adding/removing/switching planes.

### CODE REVIEW

**Comment by mlavik1** [comment]
@Karthikarc115 does this work for you?

**Comment by Karthikarc115** [comment]
> @Karthikarc115 does this work for you? 
> Just check out the "slice-measure" branch, load a volume and go to "Volume rendering" -> "Slice renderer" and click "Add plane".
> Also remember that you might need to do some changes to make sure the displayed values are correct, as I mentioned here: https://github.com/mlavik1/UnityVolumeRendering/issues/125#issuecomment-1330598007
> I'm going to add a setting fort that soon.

Sorry i was busy for some time and didn't get time to check it,will do it today

**Comment by mlavik1** [comment]
**Update:**
Slice view now looks like this:
image

Has buttons for adding XY, XZ and ZY planes as well.

Click this button and then click+drag mouse to measure distance:
image

**Comment by mlavik1** [comment]
And I've pushed another change, so the measured distance is shown in the correct units. 
You can ignore what I said about having to remove that "/ maxScale" in the code.
You should now be able to simply import a dataset, open the slice rendering window, add a slice and measure the distance.
image

Hope that works for you @Karthikarc115

**Comment by Karthikarc115** [comment]
> And I've pushed another change, so the measured distance is shown in the correct units. 
> You can ignore what I said about having to remove that "/ maxScale" in the code.
> You should now be able to simply import a dataset, open the slice rendering window, add a slice and measure the distance.
> image
> 
> Hope that works for you @Karthikarc115

Sure will try this

**Comment by mlavik1** [comment]
Great! Hope that works for you👍

**Comment by mlavik1** [comment]
I'm merging this PR now, since it seems to work fine after doing some testing.
Feel free to let me know if you notice any issues, or if you have further requests :)

**Pull request merged**
