### PR TITLE
Async loading

### LINKED ISSUE #151: Async dataset import
Importing large datasets can be very slow, and will cause the whole application to freeze.

**Suggestion:** Implement support for async import, on a separate thread. This should be optional, and possible to disable.

### PR DESCRIPTION
**Pull request by SitronX**
Support for async loading. Resolves #151 

Async option is selectable from settings:
Async

It uses scripting defined symbols:
Scripting

### CODE REVIEW

**Comment by mlavik1** [comment]
Thanks a lot for this @SitronX !
I've had a very quick look at it, and it looks really nice. Great that you added a setting for it as well :) 
I'm away tomorrow, but I'll see if I can look through the code and do some testing tomorrow evening or on Tuesday.
Talk to you soon! And thanks again :D

**Comment by SitronX** [comment]
@mlavik1 Sure, no problem :) We as a community also thank you for this amazing library. It works great :D 

Oh and ye, i mentioned it in #151  but forgot to add it here. I could not test myself Parchg and raw datasets, cause i dont have such datasets. They should work, but still include them in your tests please. Thank you.

**Comment by mlavik1** [comment]
Hi again @SitronX !
And thanks for the kind words!
Regarding RAW and PARCHG datasets: There are some in the "DataFiles" folder in the repository, and they seem to work fine! :) 

First of all, *this PR really is a big improvement!!* So thanks a lot!
I think eventually I want to make import async by default (at least in the editor functions), but that can be done later - after some more testing.

**Some feedback on this PR:**
- The `DownScaleDataAsync` appears to be exactly the same as `DownScaleData`, except it's marked as `async`. To avoid code-duplication, maybe we could remove `DownScaleDataAsync` and just use `DownScaleData` as it is, but from within a task - like this:
```csharp
await Task.Run(() =>
{
    dataset.DownScaleData();
});
```
It should also be fine to remove the call to `DownScaleDataAsync` in `FixDimensions`. Since it doesn't await I don't think the `async` keyword affects anything, and you always seem to call this function from within a task anyway, so that doesn't block the main thread then :)  

- In `DICOMImporter.cs`, the `LoadSeriesAsync` and `ImportSeriesAsync` functions have a lot of code inside a `await Task.Run(() => ...` that is identical to the code in `LoadSeries` and `ImportSeries`. Do you think that code could be moved to a separate function (`LoadSeriesInternal`, `ImportSeriesInternal`, etc.) to reduce code duplication? Then these functions will become a lot smaller and simpler :) Those internal functions wouldn't need to be `async`, since they are used from within a task, and they don't do any awaiting themselves.

The other importers also do some similar duplication of code, but I think that's fine since they are quite short and simple anyway :grin: 

Please let me know if I've misunderstood or overlooked something.

Again, thanks a lot for this PR! Looking forward to get it merged.

**Comment by SitronX** [comment]
Hello, thanks for checking it.

I think you missed one line in DownScaleDataAsync :D
async

So the loop was in other thread, but i will still change it to your solution, because it is cleaner and there is less code duplication :)

You are right with FixDimensions, the async call is not needed there, i overlooked that. 

I overall didnt want to gut your methods too much for this async support, but you are right when i look on it back. It should be better for readability if it reused code more. So i will change it as you said and ping you here when it is done.

**Comment by mlavik1** [comment]
Oh and another question:
I saw you pushed a `.vsconfig` file as well. Is that for using Visual Studio in Unity projects?

**Comment by SitronX** [comment]
> I saw you pushed a .vsconfig file as well. Is that for using Visual Studio in Unity projects?

Ohh good catch, didnt notice that. It is autogenerated file that is associated with Visual Studio. I will try to remove it in next commit.

**Comment by mlavik1** [comment]
Ok, great! :)

**Comment by SitronX** [comment]
@mlavik1 Hello
The refactoring should be finished. I went thru all my file changes so it is quite a lot of code removed, which is now being reused.

Also when you mentioned that there is parchg dataset in that folder i tried it and found culture related issue that prevented me from loading the dataset. So i also fixed it. It was difference between decimal point and decimal coma. Now it should work in every country.

**Review by mlavik1 — APPROVED** [review]

**Comment by mlavik1** [comment]
Merged!
Thanks for fixing that bug. And I didn't know about the [allowThreadedTextureCreation](https://docs.unity3d.com/ScriptReference/Texture-allowThreadedTextureCreation.html) setting!

Next, I'd like to move this out of experimental, and make import be async by default, of course after doing lots of testing.
I'm also thinking that the sync functions can just call the async ones then (thourh `Task.Run`), and block until they complete.
I'm glad you did it like this now though, since it gives us some time for testing - and this PR is quite safe to merge (import behaviour is same as before when async import is disabled).

**Comment by SitronX** [comment]
Hello @mlavik1 

While [allowThreadedTextureCreation](https://docs.unity3d.com/ScriptReference/Texture-allowThreadedTextureCreation.html) sounds nice, i dont actually think it is helping a lot, because Texture generation still slightly freezes :D But it sounded nice so i added it there :D 

> I'm also thinking that the sync functions can just call the async ones then (thourh Task.Run), and block until they complete. Does that make sense?

Yes, i have just tried it. New Task.Run didnt really worked, but what worked was this:  

asyncSyncrhonously

So here async method essentially behaved like it was sync method.

> Do you mind if I add you as a reviewer if I end up making a PR for that?

Sure, i can check it out :)

> And again: Thanks a lot for this PR!

Glad i was able to help 👋

**Comment by mlavik1** [comment]
Hi again @SitronX !

Thanks for the suggestions :)
That should work in general, but turns out it causes the main thread (and editor) to freeze when you do it in Unity. Probably be cause the main thread is blocked while waiting for the task to finish, and the task never ends up finishing because it's waiting for some async method to continue (which is scheduled from the main thread..).

I got it to use like this though: https://github.com/mlavik1/UnityVolumeRendering/blob/624eeab8b1237bdfb97ffc01f6c8698027b98a47/Assets/Scripts/VolumeData/VolumeDataset.cs#L51
Using some suggestion I found on StackOverflow :sweat_smile:

**Pull request merged**
