### PR TITLE
Image sequence import

### PR DESCRIPTION
**Pull request by MichaelOvens**
Additional import pathway for image sequences together with a couple of density import utilities.

### CODE REVIEW

**Comment by mlavik1** [comment]
Thanks a lot for the contribution!
Tested it and it works great! And the code looks good 👍 
I'll merge it in right away.

By the way, I saw that you first added ".tif" as a supported format, and removed it again since it's not supported by Unity. Is it common for image sequence data to use .tif? If so I can probably add support for that as well, by using FreeImage.

**Comment by denistribouillois** [comment]
Hey,
.tif format is super common for 3D images, at least in my work environment. I work in a lab and I get 3D images mainly from biologists from different microscops as .tif (most of the time, just multiple files, but sometimes one .tif file that contain all images).
I use a different pipeline for loading images in my application (using with this plugin https://assetstore.unity.com/packages/vfx/shaders/fullscreen-camera-effects/volume-viewer-pro-83185) but it would be super useful if you add .tif support, I was always too lazy to do it myself as I have a working pipeline (but not open-sourceable)

**Comment by mlavik1** [comment]
@denistribouillois Ok, I'll do that then! It's good timing actually, because I made an async texture importer for Unity that supports .tif just a few weeks ago: https://codeberg.org/matiaslavik/unity-async-textureimport/
I can probably just use that, or at least the FreeImage bindings I made for it.

I might be away for some days, but I'll make a task now and start working on it when I have time again.

**Comment by MichaelOvens** [comment]
I was also using Volume Viewer Pro @denistribouillois , but I actually found that @mlavik1 's looked better and was generally easier to work with!

I've got a at work involving volume rendering (no money's involved - it's higher education teaching/research experience and an exploratory collaboration with some hospitals), so you can expect me to kick through extensions I write that I reckon you'd find useful over the coming months. Feel free to accept/reject/amend them as you wish!

**Comment by denistribouillois** [comment]
Yeah I fully agree, I only kept the plugin for loading tif/dicom/nii to Texture3D.
Great to ear that this repo is getting attention and contribution!
My project is also for research, so it might be open source at some point.
In case you're interested, you can check a small video here:
https://youtu.be/0JmsRN8t97s?t=511

I made some features that would definetly make sense to share/commit to this repo:
- 3D images with multiple channels
- 4D images (3D + time)
- Histogram on GPU with a compute shader (faster than CPU)

**Comment by mlavik1** [comment]
Wow, thanks! I'm really glad to hear that 😄 
It really motivates me to see that there are people who are using this project.

@MichaelOvens That's good news! Your PRs are more than welcome!
Also, if you have feature requests or suggestions for things that could be improved, feel free to create an issue!

@denistribouillois Thanks for sharing! That "segment" feature looks really nice! Maybe that's something I should look at as well. Currently the only interaction tool I have is the cross section plane. I have been thinking of adding a cutout box too.

About "Histogram on GPU with a compute shader": So you moved the histogram calculation over to the GPU, right? That could be a big improvement, because currently that calculation is really expensive.
We could also do that with the gradient calculations too. Currently you will notice a long delay when turning on "isosurface" rendering or when enabling lighting.

**Comment by MichaelOvens** [comment]
I'm actually working on a "post-segmentation" workflow right now (users are able to highlight and select segments to interact with) but I'm relying on users having pre-segmented the data using something like 3DSlicer, so an internal segmentation tool like what @denistribouillois has made would be great!

A cutout box would be really useful!

**Comment by mlavik1** [comment]
@MichaelOvens I see! How did you get the pre-segmented data from 3DSlicer into your application? (is that a feature in DICOM maybe?)

Yes, I just made a task for the cutout box! (#32 )

**Comment by MichaelOvens** [comment]
@mlavik1 The segmentation is done in 3DSlicer using their Fast GrowCut tools ([https://www.youtube.com/watch?v=BJoIexIvtGo]) and then exported as its own 3d dataset (in user's choice of format) as a greyscale image where each segment has a different color value. To get it into my application, I load the base volume and the label volume then just duplicate the base dataset once for each segment, masking out any voxels which aren't part of the segment. This means you end up with a whole bunch of volume objects which isn't great for performance, so I'm working on a user interface whereby segments are hidden until selected from the corresponding section on the base volume.

**Comment by denistribouillois** [comment]
@mlavik1 
Yes histogram calculation is done on GPU with a compute shader, which is way faster for large images.
The code should be straightforward and easy to share, I'll make a PR.

For the gradient/light calculation, if I remember correctly you moved it from GPU to CPU to avoid overcalcuation I guess (https://github.com/mlavik1/UnityVolumeRendering/commit/f258bf24b046051e66edfd182fb002dc7c43c21f#diff-547394143ada2254be67b4ef5c602882bf0c188d2a720a4860bb658f366d8505). I ended up leaving the calculation on the GPU which was fast enought for my use case, but the precalculation could definetly be done with a compute shader as well.

@MichaelOvens 
My implementation of multichannel image could help you with your use case. I basically load the first image in the red channel, then the second image in the green channel and the third image in the blue channel. This way I can visualise 3 datasets at the same time with only one image/object.
For the segmentation tools, I have manual segmentation (but it's in VR, quite specific for my use case), and two automatic algorithms: the first one is fast but not  performant, it's a "Magic Wand" based on flood fill algorithm (https://en.wikipedia.org/wiki/Flood_fill); the second one use SimpleITK library (https://simpleitk.org/) to perform a Watershed algorithm (https://en.wikipedia.org/wiki/Watershed_(image_processing)), it's much slower but provides better results. In both case the initial input is a voxel of the volume.

I can share implementation details/code if interested.

**Comment by denistribouillois** [comment]
Actually for segments visualisation, I also made something that applies more to your use case @MichaelOvens 
After segmenting (manual or automatic) I save the selected voxels in a mask (lower resolution than the volume for performance reason) and associate the segment with a color. I can repeat and have multiple masks, for each segment.
I then create a new texture that merge all masks + colors.
In the volume rendering shader I read the texture and add colors to the main volume data

**Pull request merged**
