### PR TITLE
Partial Charge Density Rendering for VASP 5 

### PR DESCRIPTION
**Pull request by jasonks2**
Hello, I have written the file ParDatasetImporter.cs (along with ParDatasetImporterEditorWindow.cs) which allows users to upload their VASP 5 output which is named: PARCHG.*.vasp. The script reads the headers lines and contains functions to perform the math on the arrays parsed from the file.

Please see major edits in VolumeDataset.cs

Minor edits are in DatasetImporterUtility, RuntimeGui, volumerenderereditorfunctions, etc
 volumeobjectfactory (2 line change) volumerenderedfactory ( 3 lines)

There is also a current bug where I replace the functions inside VolumeObjectFactory and edit GetDataTextureInternal() to a new function I have written GetDataTextureInternalParChg()

So the RAW file doesn't render. I will be fixing it using flags.

Thank you for creating a brilliant Volume Render within Unity.

### CODE REVIEW

**Review by jasonks2 — COMMENTED** [review]
ParDataset.cs additions

**Comment by mlavik1** [comment]
Hi!
Thanks a lot for the contribution!
First of all, I'm not familiar with PARCHG, but do you have some sample datasets that I can test with? (and maybe some documentation abut it?)

It seems like you have (accidentally?) made a copy of the whole project inside a "UnityVolumeRendering-master" folder, so the diff looks a bit confusing. There are duplicates of most of the source files because of that.

Also, for this project I want to keep the code as simple as possible, and I ideally want to avoid custom code for different file formats outside of the importer code. But if I understand this correctly, you had to modify the VolumeDataset because you need to store the dataset as "double" values, right? And everything else that you had to change is a result of that, right? (because the existing code worked with int values -while you need double). Is there anything else that I missed?

**Comment by jasonks2** [comment]
> Hi!
> Thanks a lot for the contribution!
> First of all, I'm not familiar with PARCHG, but do you have some sample datasets that I can test with? (and maybe some documentation abut it?)
> 
> It seems like you have (accidentally?) made a copy of the whole project inside a "UnityVolumeRendering-master" folder, so the diff looks a bit confusing. There are duplicates of most of the source files because of that.
> 
> Also, for this project I want to keep the code as simple as possible, and I ideally want to avoid custom code for different file formats outside of the importer code. But if I understand this correctly, you had to modify the VolumeDataset because you need to store the dataset as "double" values, right? And everything else that you had to change is a result of that, right? (because the existing code worked with int values -while you need double). Is there anything else that I missed?

Hello, thank you for the reply.
I will upload the dataset into the DataFiles folder so you can see the visuals. I may have made a copy of the whole project because I didn't know if I should put my edited files separate or within the entire assets folder. Sorry for that.

I indeed did have to store the dataset as doubles because some of these density points are in scientific notation and I have to convert them to a double value. And yes I only need double array objects instead of int. Thanks again.

**Comment by mlavik1** [comment]
Ok, thanks for clarifying!

Let me know (just post a comment) when you've cleaned up the duplicate files so it's easier to review.
You can check the diff here: https://github.com/mlavik1/UnityVolumeRendering/pull/58/files
The diff should ideally just show a few files when that is fixed :)

**Comment by jasonks2** [comment]
Hello I created a new pull request and it should be easier to see the changes

**Comment by jasonks2** [comment]
Hello,

I have created a new pull request with all my edits in a separate branch.

-jason

**Pull request closed without merging**
