### PR TITLE
Parchg electron density volume renderer

### PR DESCRIPTION
**Pull request by jasonks2**
Hello I cleaned the files up so they are easily reviewed.

### CODE REVIEW

**Comment by jasonks2** [comment]
Hello, I have cleaned up the files in this pull request, my branch is "PARCHG electron density."

I plan to add some pictures of an example rendering of a VASP file.

**Comment by mlavik1** [comment]
Hi!
Thanks for making the new PR. This looks much better :smiley: 
And I'm sorry for the late reply. Things have been quite hectic here, and still are, so I won't be able to work on the project every day, but I'll do my best :) 

As I mentioned in the other PR I want to keep things as simple as possible, and avoid nearly duplicate code, so I'd like to do something about the double/single precision data.
But first I need to ask: You store all the data values as double precision floats, however in CreateTextureInternalParChg a single (or even half) precision texture format is used - not double precision (which might not be available anyway).
So could it be sufficient to use single precision floats instead? (since that's the highest precision that will be used on the GPU anyway).

I'm thinking of changing my original implementation to use floats instead of ints. Optionally, I could create a setting for allowing double precision floats, but if we don't use that in the shader anyway I suppose a normal "float" should do?
At least I want to avoid using double by default, since RAM usage will be much higher.

Again, thanks a lot for the PR. I think you have pointed out a weakness in my original implementation :)

**Comment by mlavik1** [comment]
Oh, and another question:
Do I need to set these values to something when importing the dataset?
image

I tried importing without setting them, and then it looks like this:
image

**Comment by mlavik1** [comment]
Oh, and another question:
I tried importing the PARCHG sample dataset you added, but I'm wondering which values I should insert here:
image


If I leave them as zero, it looks like this:
image

**Comment by jasonks2** [comment]
Hello,

Sorry for the late reply from me. I have been busy as well figuring out how
to pay my college debt.

I agree with you that using System.Single (aka float) is much more
efficient than System.Double. With that change each var would now be
storing 4 bytes instead of 8. ideally 200% more efficient!

Thank you for finding that out, I totally would’ve missed it. I will be
fixing that in the next PULL request when given the time (2 weeks?), please
let me know if you will use floats instead of ints on your end.

Regarding the GUI pic you sent:
You don’t have to enter values, I just ended it putting it there (useless
field).

Also, the cube is representative of the 3D density values which is correct,
the real use of the volume render is in your 2D transfer function editor
which changes the texture and it almost looks like it’s a smoothed out
molecule.

Thanks,

-Jason

**Comment by mlavik1** [comment]
Hi again!

I just merged in master. Sorry for the commit mess. My laptop broke (reinstalling now) so had to edit the files on GitHub 😅 

I see! I tried coomparing to how it looks in another vasp viewer, and now I noticed the similarities. I'll try experimenting a bit with the 2D TF editor later (oh, and I really should improve the 2D TF editor sometime. I'll make a task for it.)
Thanks for clarifying.

Actually, you don't need to worry about that yet.
I think I'll start working on changing the volume data from int to float (for all formats) today. That way I guess we can get rid of some of the functions you had to add in this PR. It should hopefully not take more than a day or two.

Another question: Where did you get the dataset from? Do you have a link to its license?
I need to add a copy of the license for all the datasets that we distribute with this project, to make sure I have the law on my side 😁

**Comment by jasonks2** [comment]
Thank you so much for changing the int to float and incorporating the downscale + averaging. I tested this branch on Unity a few days ago and I was able to load the PARCHG and RAW data sets which is great news. I also was able to enable lighting on the "electron cloud" (I don't know if it worked before). 

As far as TF2D. Perhaps I can help out with a method that inserts a Gaussian function to volume render instead of a rectangular box. (x = 0.9 (constant) and changing it to x = 0.9 * y * height * width). We can discuss more about this since this is a technique used by the VASP  volume renderer to view charge densities. 

I have contacted my prof. at uni and he says that there is no license associated (file obtained from him). I know that this file is an output of the VASP software (header lines).

I said I would work on the gui, but I am running into some errors with updating. I might have to make a function that reads the header only and then shows it on the window and then work on the gui.

But for now, I am ready to commit this branch to the master!

**Comment by mlavik1** [comment]
Thanks for the suggestion!

And thanks for the clarification.
No license usually means that nobody can use the file, but if the dataset belongs to your professor/uni and they are OK with it being used, then I'll just add a  text file stating that it has no license but permission has been granted for us (what is the name of the University btw?). Or maybe I can find another open dataset to use instead 🙂
I will take a look at this in the weekend I think. Looks like I will need to fix some more merge conflicts first 😁

**Comment by jasonks2** [comment]
The permission file sounds like a good idea, the name of the uni is University of Illinois at Urbana-Champaign. The file is from the output of a software known as VASP and that company gives out licenses to research institutes to download the software, we are only using an example data file.

I just ran into an error recently actually (after merging master -> PARCHG---Electron-Density-Volume-Renderer) where it doesn't seem to generate a visible texture. I will look more into this since I had to change some int -> float in VolumeDataset.cs then HistogramGenerator but still couldn't load the RAW or VASP dataset.

Thanks for your continued support.

**Comment by jasonks2** [comment]
^ Error fixed thank you for the nullcheck :)

**Comment by mlavik1** [comment]
Thanks for the update!

There's one more thing I'd like to fix first:
I noticed that some other VASP files fail to import because of the following reasons:
- Each lattice line can have any number of spaces separating each entry. We need to split it by space (" ") and then remove all empty items. Using LINQ we can do it like this:
bilde
- In the VASP format, some elements (such as selective dynamics and atom names) seem to be optional. So we cannot assume that the atom positions start at line 8, etc. So it's probably better to create only *one* StreamReader and then read line-by-line and check if an optional line is present or not. Since we cannot rely on the line numbers.
**Example:**
1. Read header.
2. Read scaling constant.
3. Read bravais matrix.
4. Peek next line and check if it contains N atom names. If not, skip to (5)
5. Read atom numbers.
6. Peek next line and check if it contains "Selective Dyn"
etc.

I already started working on this, so I can probably do it :)

**Comment by mlavik1** [comment]
By the way, I have one question about the `getAtomSum` function:
It seems to create a list of atom count strings, then combines this into one string and assumes that the ASCII byte size of that string will be equal to the number of atom types. Won't this break if the atom counts are for example "12 8"? Then the atom count will be 3, while there are only two atoms. Or did I misunderstand something?

Could we instead just do this?:
bilde

**Comment by jasonks2** [comment]
Thank you for pointing out some sloppy errors I made, at the time making this script I simply wanted to volume render a single file (I had some intentions for scalability For example, I used ReadLine() in contrast to ReadToEnd() which would call ~10 functions to read 55k lines 10 times).

When making setLatticeVector() I spent a bit of time exactly because there could be any number of spaces between each value. Good job on that and verifying that there are only 3 (x,y,z)

When I made this script it was intended for a a PARCHG.<nameoffile>.vasp VASP version 5 and not for VASP version 4 (After about 2 weeks of debugging one chunk of the file I just wanted to make this script work). What one author has done (implemented in perl) is to make a version flag and like you mentioned, skip to a specific line number. Here is the main reference I used: https://theory.cm.utexas.edu/vtsttools/scripts.html
(file - chg2cube.pl)


Making only one stream reader is the best idea for efficiency and I agree by checking line by line (parsing once). Basically what we are achieving is a VASP volume renderer for any output file, there are several different types such as POSCAR, elf car, CHG, PARCHG etc.

Regarding getAtomSum(). You’re right if they are 12 and 8, the size will only be 3. Another sloppy error of mine, thank you for catching this.


Please let me know where I can help and continue developing.

**Comment by jasonks2** [comment]
Here he uses an index method which shifts the position of the index based on VASP4 or VASP5 version

Screen Shot 2021-12-24 at 4 16 11 PM

**Comment by mlavik1** [comment]
Thanks for the clarifications!
Aha, so atom names are required from VASP 5.x, but were not a part of VASP 4 and earlier, right?

Thanks for the link! I'll take a loo at that too.
I think I know what I need to do now :) I'll see if I can get it done before new year!

**Comment by mlavik1** [comment]
Happy Christmas to you too! :) 

I've pushed my fixes now. I think it should be ready for merge, but please take a quick look/test to see if I messed something up 😁 
Also, I was wondering: Is there a need to have an editor window for Parchg import? Since the dimension is always specified in the dataset, there should be no need for the user to set any parameters manually, right? If so, can I remove the `ParDatasetImporterEditorWindow` class and instead make it import the dataset directly through the `ParDatasetImporter`?

Looking forward to get this merged in now!

**Comment by jasonks2** [comment]
The pushes look great I just tested it on my computer and it works. 

ParseLine() function is a great way to act as a counter variable for each line and removing the stream reader seems to be doing very well for performance, awesome.

And yes you can remove that class and start the merge!

**Comment by mlavik1** [comment]
Thank you that's nice to hear!
I'll merge this now. Thanks a lot for your great contribution :) 
Happy new year!

**Pull request merged**
