### PR TITLE
Progress reporting of async texture creation

### PR DESCRIPTION
**Pull request by mlavik1**
**Changes:**
- Added progress reporting to data texture creation
- Added progress reporting to gradient texture creation
- Added progress bar to VolumeRenderedObject's inspector
- Removed `ProgressHandler.Start` and `ProgressHandler.Finish`
- Added async versions of setters for VolumeRenderedObject:
   - `SetRenderModeAsync`
   - `SetTransferFunctionModeAsync`
   - `SetLightingEnabledAsync`
   - `SetTransferFunctionAsync`
-  Added `currentStageProgress` to `IProgressView`

image

#164

### CODE REVIEW

**Comment by mlavik1** [comment]
@SitronX Here's a PR for the issue we talked about.
Notice that I added a new `currentStageProgress` parameter to `IProgressView`. I guess you'll want to use that :)

**Comment by mlavik1** [comment]
Hi @SitronX 
Thanks for the feedback!

> It looks good. But dont you also want to add reporting to default texture creation? 

You're right, I should probably do it there as well. If I do it similar to how I did it in `CalculateValueBounds` then it shouldn't be too expensive either, so that's probably fine.

> On sidenote. This is interesting code style, i didnt even know it is possible to throw away increment from for loop like this :D

Haha, thanks! :grin:  I hesitated a bit about it, since it's not as intuitive, but do you think it's readable enough? It's probably a bit faster than the alternatives at least :)

> Also i have noticed weird scaling issue when not using simpleITK on one certain DICOM dataset

Thanks for letting me know! I did change the openDICOM importer to do the same coordinate space conversion as the SimpleITK importer. I tested a few datasets and they looked the same as when imported with SimpleITK, so I'm not sure why this one looks like that.. Is it an open dataset that I can download somewhere maybe? :)

**Comment by mlavik1** [comment]
I've updated the progress reporting now!

And I've tried reproducing the issue with datasets having different scale in SimpleITK and OpenDICOM, but I've had no luck so far.. The ones I have get *nearly* the same scale. I did notice a small mistake in the importer (which is why they were only "nearly" the same. Can you try again now? If your dataset has very few slices then that might have been the cause.

**Comment by SitronX** [comment]
>I did notice a small mistake in the importer (which is why they were only "nearly" the same. Can you try again now?

Yep, all good now. I tried it and it has correct scale now same as SimpleITK. 

>If your dataset has very few slices then that might have been the cause.

It was actually that huge 730 slice dataset that was having issues :D 

>Haha, thanks! 😁 I hesitated a bit about it, since it's not as intuitive, but do you think it's readable enough? 

When i look back on it now, it is nice compact solution, but when i read it first, it took me a while to get what is really going on :D It also kinda suprised me, cause i never saw for cycle used like that :D If it was me i would probably swap that first for cycle with while loop, cause it basically acts like it and would have that iterator variable somewhere else. But that is just personal preference i guess. And plus side, your solution teaches people that for cycle can also be used like that :D 

>It's probably a bit faster than the alternatives at least :)

Ye definetely, this is better, cause you are not checking the value everytime in that loop like me :) Although as i previously said somewhere, when i tested my variant, it added only negligable additional time (12s with reporting/10s without).

>I've updated the progress reporting now!

Yep, now it looks great. Thanks :)

**Comment by mlavik1** [comment]
>Yep, all good now. I tried it and it has correct scale now same as SimpleITK.

Great to hear! Thanks for testing :D

>  If it was me i would probably swap that first for cycle with while loop

Yes that could work too! I'll look through all this again before I set up the next release, so I'll consider changing it then.

> Ye definetely, this is better, cause you are not checking the value everytime in that loop like me :) Although as i previously said somewhere, when i tested my variant, it added only negligable additional time (12s with reporting/10s without).

Yes, probably your progress reporting callback function is pretty fast then :) If it were slower it could be more of an issue. But I guess one callback per slice should be enough 😁 

> Yep, now it looks great, thanks. PR has my blessing now haha :D

Thanks once again for your help! I'll merge this then!

**Pull request merged**
