### PR TITLE
Made async import default

### PR DESCRIPTION
**Pull request by mlavik1**
**Changes:**
- Editor: Made dataset import and data/gradient texture update  be async by default
- Created a  ´ProgressHandler´ class for tracking import progress (hierarchially), and added a progress bar for dataset import in the editor.
- Removed sync versions of functions for creating data/gradient textures - the sync versions now call the async code, and block until finished.
- VolumeDataset: Replaced `currentlyCreatingGradient` with a semaphore.
- Removed the AsyncManager, since async import is now on by default.

image

### CODE REVIEW

**Comment by mlavik1** [comment]
Hi again @SitronX !
Would you mind having a quick look at this whenever you have time? :grin: 
No hurry at all! I'll probably not merge it for some days, since I need to test thoroughly - on various platforms.

Since async import is now on by default, I ended up removing the AsyncManager - does that sound right?

I also added a progress handler and progress bar for the editor.
If you wish to show a VR progress bar in your application you should be able to implement the `IProgressView` interface and assign it to a `ProgressHandler` that you pass to the importer. Please let me know if you have any feedback about this system!

Have a great day :)

**Comment by SitronX** [comment]
Hello @mlavik1 
This sounds great. That progress bar is looking like great addition. In my app i only had message informing user that "Dataset loading" "Texture loading" so the percent progress will be great addition :D.

>Since async import is now on by default, I ended up removing the AsyncManager 

Ye sure, it was just a placeholder.

I just quickly loaded it and it seems you are using too advanced language stuff, which breaks older versions :D
upgrade

Also cannot find Progress
upgrade2

Is it something specific from the C# 8.0 ? So the upgrade will be needed? I will try look into the code tomorrow or day after.

**Comment by mlavik1** [comment]
Hi  @SitronX, thanks for the feedback!
I was developing in Unity 2020 - should probably use an older version when developing :sweat_smile: 

Turns out `using` was added in C# 8, so I'll probably need to use the old scoped [using statement](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using) instead for now.

And it seems `Progress` was added in Unity 2020, so I'll probably just switch to using the `NullProgressHandler` in older versions instead :)

**Comment by mlavik1** [comment]
**Update:** Just pushed some fixes, so now it works in Unity 2019 :)

Note: You'll need Unity 2020+ to see the progress bar in the editor.

**Comment by SitronX** [comment]
Hello @mlavik1 ,
so i looked into the code and it is looking great. Nice overall refactoring.

In <b>VolumeDataset.cs</b>  i only noticed that `GetGradientTexture()` , `CreateTextureInternal()` and `CreateGradientTextureInternal()` can be now probably deleted, they are not being used by anything after your refactor. 

Also in the future it might be worth to look into methods that are calling `GetDataTexture()`. They could probably also benefit from async variant. If you wanted the complete async package :D

I was also thinking, adding status report to both texture generation, especially in this expensive for loop would be absolutely great to-have feature, since you have implemented that progress window now.

loop

Because now people usually use (i guess) SimpleITK for import, which is extremely quick and all waiting is usually spent on texture generation.

Otherwise everything seems to be good and it is now not giving errors in previous Unity versions :)

**Comment by mlavik1** [comment]
Oh, nice catch!
I forgot those completely. Will delete them :)
I think I'll keep `GetGradientTexture` though since it's already public, and might be in use by others already.

And that's a good idea!
Are you mainly thinking about progress reporting for texture creating during dataset import then?
I'll finish testing this PR and merge it first, and then that can go in a separate PR afterwards :)

**Comment by SitronX** [comment]
>I think I'll keep GetGradientTexture though since it's already public, and might be in use by others already.

Oh ye, right, havent thought about that, you are right.

>Are you mainly thinking about progress reporting for texture creating during dataset import then?
                                          
Ye, that moment when dataset basically becomes white square, when it is loading the main texture. If it showed progress with that for loop (picture above), it would be great. That for loop takes like 90% of the time in that method. Due to the usual amount of elements, if it reported lets say every million passed, so progress reporting doesnt slow loading too much, that would be great. 

https://github.com/mlavik1/UnityVolumeRendering/blob/b64aaceb7774d75d72db6fb54dae9c89325cc709/Assets/Scripts/VolumeData/VolumeDataset.cs#L189

There is also that texture gradient generation which would also benefited from that. 

https://github.com/mlavik1/UnityVolumeRendering/blob/b64aaceb7774d75d72db6fb54dae9c89325cc709/Assets/Scripts/VolumeData/VolumeDataset.cs#L264

The dataset downscale process reporting would be also nice, but it is not that important like these two texture generations mentioned above :D

Of course if you feel like doing it, to me it seems like great addition.

**Comment by mlavik1** [comment]
Yes, that's a great point!
I made a task for it #164.
Also a related task (#163) would be to show either a progress bar or a "generating texture" message in the custom inspector of `VolumeRenderedObject` when generating these textures. I just managed to confuse myself  - I thought the "enable lighting" feature was broken, but then realised it was just taking some time to create the texture :sweat_smile:

**Comment by SitronX** [comment]
>  I just managed to confuse myself - I thought the "enable lighting" feature was broken, but then realised it was just taking some time to create the texture 😅

And that is exactly why texture report will be such a great addition :D

**Comment by mlavik1** [comment]
Merged! :)

**Pull request merged**
